name: Deploy to Firebase Hosting and Cloud Functions on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js (Version 20)
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RAZZ3_FB }}'
          channelId: live
          projectId: razz3-fb
      # Add this step to deploy Cloud Functions
      - name: Deploy Cloud Functions
        uses: google-github-actions/deploy-cloud-functions@v0.7.0
        with:
          credentials: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RAZZ3_FB }}
          project_id: razz3-fb
          source_dir: functions
          # If deploying all functions from the functions directory, you might not need the name field.
          # If the action requires a name, specify the main function name or adjust according to the action's documentation.
